services:
  dbtest:
    image: mysql:8.0.42
    restart: always
    environment:
      - MYSQL_DATABASE=kopichat
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d:z
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -ppassword --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
  unit_tests:
    image: golang:1.24-bookworm
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=dbtest
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=kopichat
      - CGO_ENABLED=0
    working_dir: /src
    depends_on:
      dbtest:
        condition: service_healthy
    entrypoint: ["/usr/local/go/bin/go"] 
    command: go mod tidy      
    volumes:
      - .:/src:rw           