services:
  db:
    image: mysql:8
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=kopichat
      - MYSQL_ROOT_PASSWORD= password
    ports:
      - "3306:3306"
volumes:
  db-data: